export const gameStateZero = {
	name: '',
	dealer: '',
	betRound: 'pre-flop',
	decideWinner: false,
	inRound: false,
	claimed: false,
	vote: false,
	voteType: '',
	voteInfo: {},
	pots: {},
	players: new Set(),
	toPlay: { player: '', owed: 0 },
	settings: {},
	options: {},
}
